---
image:
  repository: lsstsqre/kafka-efd-demo
  tag: latest
  pullPolicy: Always

env:
  broker: "confluent-cp-kafka-headless.kafka:9092"
  schemaRegistry: "http://confluent-cp-schema-registry.kafka:8081"
  kafkaConnect: "http://confluent-cp-kafka-connect.kafka:8083"

secret:
  githubUser: ${github_user}
  githubToken: ${github_token}
